// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBbOkPOpXOhTY4b8H-sE9J_G8I4LPNK50',
    appId: '1:609491543675:web:3074680705028da6ebe4de',
    messagingSenderId: '609491543675',
    projectId: 'aviz-18397',
    authDomain: 'aviz-18397.firebaseapp.com',
    storageBucket: 'aviz-18397.appspot.com',
    measurementId: 'G-6SBT8VXSFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI0N_PgIHJnC5Qh1Oe1hLFOXk8AaePv4k',
    appId: '1:609491543675:android:e48704b4c4849659ebe4de',
    messagingSenderId: '609491543675',
    projectId: 'aviz-18397',
    storageBucket: 'aviz-18397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGGNhX1n2ggU5msM8ksg-KdVQNdrh0ZPc',
    appId: '1:609491543675:ios:284ddc4aa69cbba0ebe4de',
    messagingSenderId: '609491543675',
    projectId: 'aviz-18397',
    storageBucket: 'aviz-18397.appspot.com',
    iosBundleId: 'com.example.task1',
  );
}
